
###TEST GET / WEBSITE

GET http://localhost:8383


### TEST GET /dashboard WEBSITE
GET http://localhost:8383/dashboard

### GET DATA Endpoint
GET http://localhost:8383/api/data

### POST Data Endpoint (Add a User)
POST http://localhost:8383/api/data
Content-Type: application/json

{
  "name": "Dipto"
}

### DELETE Data Endpoint (Remove Last User)
DELETE http://localhost:8383/api/data


### Health Check
GET http://localhost:8383/health

### Get All Cars
GET http://localhost:8383/api/cars

### Add New Car Entry
POST http://localhost:8383/api/cars
Content-Type: application/json

{
  "car_id": "C002",
  "serial_number": "SN67890",
  "entry_time": "2025-10-26T10:30:00Z",
  "exit_time": null
}
